package com.destructioncatalyst.einsteinspuzzle.view;

import com.destructioncatalyst.einsteinspuzzle.controller.button.FeatureButtonController;
import com.destructioncatalyst.einsteinspuzzle.view.compatibility.IPanelContainer;
import com.destructioncatalyst.einsteinspuzzle.view.compatibility.tables.IFullyMutableTable;
import com.destructioncatalyst.einsteinspuzzle.view.swingcomponents.IPanelGenerator;
import com.destructioncatalyst.einsteinspuzzle.view.swingcomponents.JOptionPaneMessagePopup;
import com.destructioncatalyst.einsteinspuzzle.view.swingcomponents.tables.AttributeTable;

import javax.swing.*;
import java.awt.*;

public class FeaturePanelGenerator implements IPanelGenerator {

    private JPanel panel;
    private JLabel insertAttribLabel;
    private JScrollPane scrollPane;
    private JButton nextButton;
    private JTable table1;
    private JButton helpButton;
    private final int dimension;
    private final int objectCount;


    public FeaturePanelGenerator(int dimension, int objectCount, IPanelContainer containerFrame) {

        this.dimension = dimension;
        this.objectCount = objectCount;

        $$$setupUI$$$();

        scrollPane.getVerticalScrollBar().setUnitIncrement(10);
        scrollPane.getHorizontalScrollBar().setUnitIncrement(10);

        nextButton.addActionListener(e ->
                new FeatureButtonController((IFullyMutableTable) table1,
                        containerFrame,
                        new JOptionPaneMessagePopup()).actionPerformed()
        );

    }

    @Override
    public JPanel getPanel() {

        return panel;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        final JScrollPane scrollPane1 = new JScrollPane();
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 4, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane1.setViewportView(panel);
        insertAttribLabel = new JLabel();
        Font insertAttribLabelFont = this.$$$getFont$$$(null, -1, 20, insertAttribLabel.getFont());
        if (insertAttribLabelFont != null) insertAttribLabel.setFont(insertAttribLabelFont);
        insertAttribLabel.setHorizontalAlignment(0);
        insertAttribLabel.setHorizontalTextPosition(0);
        insertAttribLabel.setText("Введите возможные значения аттрибутов:");
        panel.add(insertAttribLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPane = new JScrollPane();
        scrollPane.setHorizontalScrollBarPolicy(30);
        scrollPane.setVerticalScrollBarPolicy(20);
        panel.add(scrollPane, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        table1.setFocusCycleRoot(false);
        scrollPane.setViewportView(table1);
        nextButton = new JButton();
        nextButton.setHorizontalAlignment(0);
        nextButton.setHorizontalTextPosition(2);
        nextButton.setMargin(new Insets(5, 5, 5, 5));
        nextButton.setText("Далее");
        nextButton.setVerticalAlignment(0);
        nextButton.setVerticalTextPosition(3);
        panel.add(nextButton, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, -1), null, 0, false));
        helpButton = new JButton();
        helpButton.setHorizontalAlignment(0);
        helpButton.setHorizontalTextPosition(2);
        helpButton.setMargin(new Insets(5, 5, 5, 5));
        helpButton.setText("Помощь");
        helpButton.setVerticalAlignment(0);
        helpButton.setVerticalTextPosition(3);
        panel.add(helpButton, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    private void createUIComponents() {
        table1 = new AttributeTable(AttributeTable.generateTableModel(dimension, objectCount));

    }
}
